// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h8C9fz9kVsxnVEjHjpK7So
// Component: qRWhCZAizyPk

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NutreatsBlueButton from "../../NutreatsBlueButton"; // plasmic-import: uIhZslhj_xpS/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: h8C9fz9kVsxnVEjHjpK7So/projectcss
import sty from "./PlasmicEmailSender.module.css"; // plasmic-import: qRWhCZAizyPk/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: G_BuaGkhbbHB/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: NdQ8js2OiFj1/icon

createPlasmicElementProxy;

export type PlasmicEmailSender__VariantMembers = {};
export type PlasmicEmailSender__VariantsArgs = {};
type VariantPropType = keyof PlasmicEmailSender__VariantsArgs;
export const PlasmicEmailSender__VariantProps = new Array<VariantPropType>();

export type PlasmicEmailSender__ArgsType = {
  sendEmail?: () => void;
  toEmail?: string;
  subject?: string;
};
type ArgPropType = keyof PlasmicEmailSender__ArgsType;
export const PlasmicEmailSender__ArgProps = new Array<ArgPropType>(
  "sendEmail",
  "toEmail",
  "subject"
);

export type PlasmicEmailSender__OverridesType = {
  root?: Flex__<"div">;
  nutreatsBlueButton?: Flex__<typeof NutreatsBlueButton>;
};

export interface DefaultEmailSenderProps {
  sendEmail?: () => void;
  toEmail?: string;
  subject?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicEmailSender__RenderFunc(props: {
  variants: PlasmicEmailSender__VariantsArgs;
  args: PlasmicEmailSender__ArgsType;
  overrides: PlasmicEmailSender__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <NutreatsBlueButton
        data-plasmic-name={"nutreatsBlueButton"}
        data-plasmic-override={overrides.nutreatsBlueButton}
        className={classNames("__wab_instance", sty.nutreatsBlueButton)}
        color={"blue"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "nutreatsBlueButton"],
  nutreatsBlueButton: ["nutreatsBlueButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  nutreatsBlueButton: typeof NutreatsBlueButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicEmailSender__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicEmailSender__VariantsArgs;
    args?: PlasmicEmailSender__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicEmailSender__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicEmailSender__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicEmailSender__ArgProps,
          internalVariantPropNames: PlasmicEmailSender__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicEmailSender__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicEmailSender";
  } else {
    func.displayName = `PlasmicEmailSender.${nodeName}`;
  }
  return func;
}

export const PlasmicEmailSender = Object.assign(
  // Top-level PlasmicEmailSender renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nutreatsBlueButton: makeNodeComponent("nutreatsBlueButton"),

    // Metadata about props expected for PlasmicEmailSender
    internalVariantProps: PlasmicEmailSender__VariantProps,
    internalArgProps: PlasmicEmailSender__ArgProps
  }
);

export default PlasmicEmailSender;
/* prettier-ignore-end */
