// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h8C9fz9kVsxnVEjHjpK7So
// Component: ArsQWkme7OfH

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import ParallaxWrapper from "../../ParallaxWrapper"; // plasmic-import: LSOQ6y4UJW7P/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import Navbar from "../../Navbar"; // plasmic-import: Evt7duOGgV1K/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import Card from "../../Card"; // plasmic-import: sEf96cT00Uo9/component

import { useScreenVariants as useScreenVariantszwwmRsht6Acu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zwwmRsht6Acu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: h8C9fz9kVsxnVEjHjpK7So/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: ArsQWkme7OfH/css

import Icons8WhatsappSvgIcon from "./icons/PlasmicIcon__Icons8WhatsappSvg"; // plasmic-import: TTdphk2aWAOK/icon
import Icons8FacebookSvgIcon from "./icons/PlasmicIcon__Icons8FacebookSvg"; // plasmic-import: 57BKQaSU873k/icon
import EnvelopeSvgIcon from "./icons/PlasmicIcon__EnvelopeSvg"; // plasmic-import: uByOaSALkISv/icon
import Icons8Instagram1SvgIcon from "./icons/PlasmicIcon__Icons8Instagram1Svg"; // plasmic-import: y04MRV0yjGVB/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  puntosDeVenta?: Flex__<"div">;
  h1?: Flex__<"h1">;
  contacto?: Flex__<"section">;
  section?: Flex__<"section">;
  mision?: Flex__<"div">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          { category: "Jerky" },
          { category: "Masticables" },
          { category: "Deshidratados" }
        ]
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszwwmRsht6Acu()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicHomepage.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicHomepage.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__dWLkb)}
            id={"home"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__er3Fj)}>
              <ParallaxWrapper
                className={classNames(
                  "__wab_instance",
                  sty.parallaxWrapper__hKopt
                )}
                speed={20}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__eHVvU)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"eager"}
                  src={{
                    src: "/plasmic/nutreats/images/img03211Png.png",
                    fullWidth: 5410,
                    fullHeight: 4359,
                    aspectRatio: undefined
                  }}
                />
              </ParallaxWrapper>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___05Wng)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nePv9
                )}
              >
                {"Descubr\u00ed"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__okek0
                )}
              >
                {"NUTREATS"}
              </div>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__tKc1V)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "80px"
                    : "150px"
                }
                loading={"lazy"}
                src={{
                  src: "/plasmic/nutreats/images/asset144XPng.png",
                  fullWidth: 13955,
                  fullHeight: 11947,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__t8DkW)}
            duration={0.8}
            reverse={false}
            triggerOnce={false}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />
          </Reveal>
          <div className={classNames(projectcss.all, sty.freeBox__o8Z0S)}>
            <Reveal
              className={classNames("__wab_instance", sty.reveal___49Xkw)}
              duration={500}
              triggerOnce={true}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__sT3Q4)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hKGl
                  )}
                >
                  {"En Nutreats, solo lo mejor para tu mascota"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kbkpM
                  )}
                >
                  {
                    "Garantizamos la m\u00e1xima calidad con treats elaborados con carne fresca premium de consumo humano. Salud, sabor y felicidad en cada bocado"
                  }
                </div>
              </Stack__>
            </Reveal>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jPr1T)}
            >
              <ParallaxWrapper
                className={classNames(
                  "__wab_instance",
                  sty.parallaxWrapper__lgRWa
                )}
                speed={10}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___6YpRs)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___0IWi)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/nutreats/images/img8989Png.png",
                      fullWidth: 8120,
                      fullHeight: 5964,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </ParallaxWrapper>
              <ParallaxWrapper
                className={classNames(
                  "__wab_instance",
                  sty.parallaxWrapper__uxg6P
                )}
                speed={30}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___2Nh9S)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__qH8Hn)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/nutreats/images/img0810Png.png",
                      fullWidth: 6711,
                      fullHeight: 5786,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </ParallaxWrapper>
              <ParallaxWrapper
                className={classNames(
                  "__wab_instance",
                  sty.parallaxWrapper__dvkhx
                )}
                speed={10}
              >
                <div className={classNames(projectcss.all, sty.freeBox__zYyqf)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__j0ZS)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"eager"}
                    src={{
                      src: "/plasmic/nutreats/images/img8715Jpg.jpg",
                      fullWidth: 6108,
                      fullHeight: 4640,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </ParallaxWrapper>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__cbFdd)}>
            <div className={classNames(projectcss.all, sty.columns___0WUGc)}>
              <div className={classNames(projectcss.all, sty.column__uV8B5)}>
                <div className={classNames(projectcss.all, sty.freeBox__qqIc0)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rkbO2
                    )}
                  >
                    {
                      "Ofrecemos una variedad de sabores y tama\u00f1os para satisfacer los gustos y necesidades de tu mascota."
                    }
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__oNahZ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "150px"
                        : hasVariant(globalVariants, "screen", "medium")
                        ? "300px"
                        : hasVariant(globalVariants, "screen", "laptop")
                        ? "500px"
                        : "500px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/nutreats/images/sellos4XPng.png",
                      fullWidth: 1867,
                      fullHeight: 831,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              </div>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__euZg)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"eager"}
              src={{
                src: "/plasmic/nutreats/images/img0513Png.png",
                fullWidth: 6711,
                fullHeight: 4474,
                aspectRatio: undefined
              }}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__anAE)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__elvub
              )}
            >
              {"Jerky"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oeMxo
              )}
            >
              {
                "Nuestros Jerky\u2019s est\u00e1n hechos con carne fresca premium, deshidratada bajo temperaturas controladas para conservar todo su sabor y valor nutricional. Disponibles en diferentes presentaciones, perfectos para consentir a tu mascota"
              }
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__mUZdR)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__ggYiS)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__u7W4C)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eZtbj
                  )}
                >
                  {"Jerky Treats"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__u4Qq0
                  )}
                >
                  {
                    "Tiras de carne grandes ideadas para perros de todos los tama\u00f1os"
                  }
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__zMOl)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/postNuevosJerkys02Png.png",
                  fullWidth: 4500,
                  fullHeight: 3365,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gElEx)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xmcjb)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ped0Y
                  )}
                >
                  {"Jerky Bites"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__srsZ
                  )}
                >
                  {
                    "Carne en trocitos, ideal para gatos y perros de razas peque\u00f1as"
                  }
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__kYpnP)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/mesaDeTrabajo8Png2.png",
                  fullWidth: 1080,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__vl2E9)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qAfTd)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__faOm
                  )}
                >
                  {"Jerky Box"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Ub3D
                  )}
                >
                  {"3 sabores diferentes de carne en un empaque \u00fanico"}
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__z5Y7P)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/boxPng3.png",
                  fullWidth: 995,
                  fullHeight: 707,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___49Rm2)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__feQve
              )}
            >
              {"Masticables"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__icYmq
              )}
            >
              {
                "Disponibles en distintos tama\u00f1os, texturas, grados de dureza y niveles de dificultad, nuestros snacks masticables ofrecen una experiencia adaptada a las necesidades y gustos de tu mascota"
              }
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__khTuc)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__owdFl)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__p3At2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cPma9
                  )}
                >
                  {"Patitas Mix"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wwjrM
                  )}
                >
                  {"Mix de patas de pollo y patas de conejo"}
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__n4M4B)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/patitiasMixPng2.png",
                  fullWidth: 1080,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__p9O9J)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dyXd8)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pr2X
                  )}
                >
                  {"Orejas de cerdo"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0II7S
                  )}
                >
                  {"Orejas de cerdo deshidratadas de elasticidad media alta"}
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__dvxPl)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/orejasPng.png",
                  fullWidth: 1080,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___6JoJ8)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ay32K)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ar5Bp
                  )}
                >
                  {"Mondongo"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yGMsJ
                  )}
                >
                  {"Tiras de mondongo deshidratado"}
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__bBpCz)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/mondongoPng.png",
                  fullWidth: 1080,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xMBc)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__z3SfN)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "200px"
                  : hasVariant(globalVariants, "screen", "medium")
                  ? "250px"
                  : "300px"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/nutreats/images/zommiesLogoSvg.svg",
                fullWidth: 649.25,
                fullHeight: 128.8,
                aspectRatio: 5.040761
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__hcYzx
              )}
            >
              {
                "\u00a1Una explosi\u00f3n de sabores y diversi\u00f3n! Es nuestra versi\u00f3n Mix de premios y masticables dise\u00f1ados para complacer los gustos y preferencias de cada gato y peludito"
              }
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__bupCi)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__mcKJc)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cFosq)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jhYpi
                  )}
                >
                  {"Chewies"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__waOny
                  )}
                >
                  {
                    "El mix de masticables m\u00e1s sabroso, dise\u00f1ado para mantener a tu peludo entretenido y feliz."
                  }
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___1Jjdj)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/patitiasMixPng2.png",
                  fullWidth: 1080,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___8AHnl)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__czwWg)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3NR6R
                  )}
                >
                  {"Bites"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tp6FO
                  )}
                >
                  {
                    "Mix dise\u00f1ado para los m\u00e1s exigentes, trozos de carnes del tama\u00f1o perfecto para un bocado, ideal para gatos y perros de raza mini"
                  }
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__eiarm)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/img0719Png.png",
                  fullWidth: 5295,
                  fullHeight: 4528,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__feExc)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__lKzT6)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o9EAa
                  )}
                >
                  {"Treats"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9Nk7J
                  )}
                >
                  {
                    "Mix de carnes y masticables, cortados en tiras largas que se adaptan al tama\u00f1o y las preferencias de la mascota"
                  }
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__iMtWl)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/img07411Png.png",
                  fullWidth: 3653,
                  fullHeight: 3924,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jeVZt)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rFui4)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dVoLe
                  )}
                >
                  {"To Go"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wjMeX
                  )}
                >
                  {
                    "Tu mix de jerkys favorito en una presentaci\u00f3n ideal para paseos o durante actividades diarias."
                  }
                </div>
              </Stack__>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ucC2Q)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"eager"}
                src={{
                  src: "/plasmic/nutreats/images/img0734Png.png",
                  fullWidth: 4999,
                  fullHeight: 3655,
                  aspectRatio: undefined
                }}
              />
            </Stack__>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__zo5E3)}
            id={"puntos-de-venta"}
          >
            <div
              data-plasmic-name={"puntosDeVenta"}
              data-plasmic-override={overrides.puntosDeVenta}
              className={classNames(projectcss.all, sty.puntosDeVenta)}
              id={"puntos-de-venta"}
            >
              <div className={classNames(projectcss.all, sty.column__deDjZ)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Puntos de Venta"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1HbsW
                  )}
                >
                  {
                    "Encontranos en los diferentes puntos de venta en los que distribuimos nuestro producto. Cada d\u00eda trabajamos para llegar a m\u00e1s lugares"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___990Jd)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ejSci)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "232px"
                      : hasVariant(globalVariants, "screen", "medium")
                      ? "auto"
                      : "379px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"80%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/nutreats/images/asset1Svg2.svg",
                    fullWidth: 146,
                    fullHeight: 150,
                    aspectRatio: 0.972871
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9JyYw
                  )}
                >
                  {""}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__rhyY)}>
              <div className={classNames(projectcss.all, sty.freeBox__rcpst)}>
                <div className={classNames(projectcss.all, sty.freeBox__riPNp)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qCndx
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Escaz\u00fa"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___55Yrt
                    )}
                  >
                    {"Perrhijos y m\u00e1s"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button___8ZUz4)}
                    onClick={async () => {
                      const $steps = {};

                      $steps["goToHttpsMapsAppGooGl8Zn6AachtEvga4P38"] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/8Zn6AachtEVGA4p38"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToHttpsMapsAppGooGl8Zn6AachtEvga4P38"] !=
                          null &&
                        typeof $steps[
                          "goToHttpsMapsAppGooGl8Zn6AachtEvga4P38"
                        ] === "object" &&
                        typeof $steps["goToHttpsMapsAppGooGl8Zn6AachtEvga4P38"]
                          .then === "function"
                      ) {
                        $steps["goToHttpsMapsAppGooGl8Zn6AachtEvga4P38"] =
                          await $steps[
                            "goToHttpsMapsAppGooGl8Zn6AachtEvga4P38"
                          ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mvw3R
                      )}
                    >
                      {"Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__jzqX4)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___61WEf
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Multiplaza Escaz\u00fa"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rzUoy
                    )}
                  >
                    {"Mercado 83"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__jOlIf)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/fiiSZoZnWXdhf6Hc7"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bPDt
                      )}
                    >
                      {"Ir al Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__d7VA)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xi557
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Multiplaza Curridabat"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x8JV
                    )}
                  >
                    {"Mercado 83"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__dh2Gi)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/JvynHzUZSsf2f4dLA"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s90RA
                      )}
                    >
                      {"Ir al Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wWYq)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cdqfU
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Plaza Lincoln"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vg1Vv
                    )}
                  >
                    {"Mercado 83"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__faMr6)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/EUDp21Z7F3eu5AkHA"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jqA4P
                      )}
                    >
                      {"Ir al Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__aoBa)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sMc7J
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Mall Ox\u00edgeno"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gbyut
                    )}
                  >
                    {"Mercado 83"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__eUyJh)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/cQsb1wc4Q3dK8BG5A"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nhyT9
                      )}
                    >
                      {"Ir al Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__awTyN)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qHT
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Consultas a domicilio"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns___69U5D)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__glhz7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kO3Ym
                        )}
                      >
                        {"Doctora Morera"}
                      </div>
                    </div>
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__gr8)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://www.instagram.com/dra.morera?igsh=MTVuc3p6b2EwdHRkcg=="
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wfTd4
                      )}
                    >
                      {"Ir al sitio"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__fh8M7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__imzT
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Rohmoser"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lLkVp
                    )}
                  >
                    {"Besal\u00fa Mercat"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__ovnAm)}
                    onClick={async () => {
                      const $steps = {};

                      $steps["goToHttpsMapsAppGooGlONxkqbAqsmnMKkdp8"] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/tF3BeD1dcYEBCvD8A"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToHttpsMapsAppGooGlONxkqbAqsmnMKkdp8"] !=
                          null &&
                        typeof $steps[
                          "goToHttpsMapsAppGooGlONxkqbAqsmnMKkdp8"
                        ] === "object" &&
                        typeof $steps["goToHttpsMapsAppGooGlONxkqbAqsmnMKkdp8"]
                          .then === "function"
                      ) {
                        $steps["goToHttpsMapsAppGooGlONxkqbAqsmnMKkdp8"] =
                          await $steps[
                            "goToHttpsMapsAppGooGlONxkqbAqsmnMKkdp8"
                          ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xtiLy
                      )}
                    >
                      {"Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8Suii)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r5OZ
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Santo Domingo"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__diVjh
                    )}
                  >
                    {"Pets Garden"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__a0H3R)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/4fATnrpDjgVjfxHc7"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8E2Oj
                      )}
                    >
                      {"Ir al Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__v3Tx8)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bQWu4
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Barrio Escalante"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zGtCe
                    )}
                  >
                    {"Paws & Co"}
                  </div>
                  <AntdButton
                    className={classNames("__wab_instance", sty.button__qo3Ct)}
                    onClick={async () => {
                      const $steps = {};

                      $steps[
                        "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                      ] = true
                        ? (() => {
                            const actionArgs = {
                              destination:
                                "https://maps.app.goo.gl/NPFMfWdAnGZxJ3su6"
                            };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                __nextRouter?.push(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] != null &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] === "object" &&
                        typeof $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ].then === "function"
                      ) {
                        $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ] = await $steps[
                          "goToHttpsTiendacrManchasComSnackNutreatsOrejaEnteraPSkuId1412"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fVy4L
                      )}
                    >
                      {"Ir al Ir a la ubicaci\u00f3n"}
                    </div>
                  </AntdButton>
                </div>
              </div>
            </div>
          </div>
          <section
            data-plasmic-name={"contacto"}
            data-plasmic-override={overrides.contacto}
            className={classNames(projectcss.all, sty.contacto)}
            id={"contacto"}
          >
            <div
              className={classNames(projectcss.all, sty.columns__yfVis)}
              id={"ubicaciones"}
            >
              <div className={classNames(projectcss.all, sty.column___8N7J8)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fqTeF
                  )}
                >
                  {"Cont\u00e1ctenos"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uxoy4
                  )}
                >
                  {
                    "Contactanos para hacer pedidos, solicitudes especiales, y seguinos en nuestras redes para conocer sobre promociones."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__oSx7M)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ncoBe)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "146px"
                      : "388px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"80%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/nutreats/images/asset1Svg3.svg",
                    fullWidth: 129,
                    fullHeight: 150,
                    aspectRatio: 0.860574
                  }}
                />
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__fSttq)}
            >
              <div className={classNames(projectcss.all, sty.column__umBr2)}>
                <Icons8WhatsappSvgIcon
                  className={classNames(projectcss.all, sty.svg__urn2Y)}
                  onClick={async event => {
                    const $steps = {};

                    $steps[
                      "goToHttpsApiWhatsappComMessageWt4I5Wn5Z4Mok1Autoload1AppAbsent0"
                    ] = true
                      ? (() => {
                          const actionArgs = {
                            destination:
                              "https://api.whatsapp.com/message/WT4I5WN5Z4MOK1?autoload=1&app_absent=0"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps[
                        "goToHttpsApiWhatsappComMessageWt4I5Wn5Z4Mok1Autoload1AppAbsent0"
                      ] != null &&
                      typeof $steps[
                        "goToHttpsApiWhatsappComMessageWt4I5Wn5Z4Mok1Autoload1AppAbsent0"
                      ] === "object" &&
                      typeof $steps[
                        "goToHttpsApiWhatsappComMessageWt4I5Wn5Z4Mok1Autoload1AppAbsent0"
                      ].then === "function"
                    ) {
                      $steps[
                        "goToHttpsApiWhatsappComMessageWt4I5Wn5Z4Mok1Autoload1AppAbsent0"
                      ] = await $steps[
                        "goToHttpsApiWhatsappComMessageWt4I5Wn5Z4Mok1Autoload1AppAbsent0"
                      ];
                    }
                  }}
                  role={"img"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__vcti9)}>
                <Icons8FacebookSvgIcon
                  className={classNames(projectcss.all, sty.svg__kl1Ps)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToHttpsMFacebookComNutreatsCr"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: "https://m.facebook.com/nutreats.cr"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHttpsMFacebookComNutreatsCr"] != null &&
                      typeof $steps["goToHttpsMFacebookComNutreatsCr"] ===
                        "object" &&
                      typeof $steps["goToHttpsMFacebookComNutreatsCr"].then ===
                        "function"
                    ) {
                      $steps["goToHttpsMFacebookComNutreatsCr"] = await $steps[
                        "goToHttpsMFacebookComNutreatsCr"
                      ];
                    }
                  }}
                  role={"img"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__riLhl)}>
                <EnvelopeSvgIcon
                  className={classNames(projectcss.all, sty.svg__ycV4J)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToMailtoNutreatsCrGmailCom"] = true
                      ? (() => {
                          const actionArgs = {
                            destination: "mailto:nutreats.cr@gmail.com"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToMailtoNutreatsCrGmailCom"] != null &&
                      typeof $steps["goToMailtoNutreatsCrGmailCom"] ===
                        "object" &&
                      typeof $steps["goToMailtoNutreatsCrGmailCom"].then ===
                        "function"
                    ) {
                      $steps["goToMailtoNutreatsCrGmailCom"] = await $steps[
                        "goToMailtoNutreatsCrGmailCom"
                      ];
                    }
                  }}
                  role={"img"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__rPQgJ)}>
                <Icons8Instagram1SvgIcon
                  className={classNames(projectcss.all, sty.svg___8VDqW)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToHttpsWwwInstagramComNutreatsCr"] = true
                      ? (() => {
                          const actionArgs = {
                            destination:
                              "https://www.instagram.com/nutreats.cr/"
                          };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHttpsWwwInstagramComNutreatsCr"] != null &&
                      typeof $steps["goToHttpsWwwInstagramComNutreatsCr"] ===
                        "object" &&
                      typeof $steps["goToHttpsWwwInstagramComNutreatsCr"]
                        .then === "function"
                    ) {
                      $steps["goToHttpsWwwInstagramComNutreatsCr"] =
                        await $steps["goToHttpsWwwInstagramComNutreatsCr"];
                    }
                  }}
                  role={"img"}
                />
              </div>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
            id={"mision"}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"mision"}
              data-plasmic-override={overrides.mision}
              hasGap={true}
              className={classNames(projectcss.all, sty.mision)}
            >
              <div className={classNames(projectcss.all, sty.column__ngL5S)}>
                <Card
                  className={classNames("__wab_instance", sty.card___2WecS)}
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ncla4
                      )}
                    >
                      {"Misi\u00f3n"}
                    </div>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bGfoy
                    )}
                  >
                    {
                      "Nuestra misi\u00f3n es ofrecerle a los consumidores un producto que no represente un peligro para sus mascotas. Para Nutreats, es una prioridad la salud por lo que nuestra filosof\u00eda se basa en fabricar bocadillos totalmente naturales, donde el \u00fanico ingrediente es carne fresca, s\u00faper premium de consumo humano. Tenemos clara la naturaleza carn\u00edvora de los perros y gatos, por lo que optamos por ofrecer carne deshidratada sin ning\u00fan tipo de aditivo o proceso que prolongue su vida \u00fatil."
                    }
                  </div>
                </Card>
              </div>
              <div className={classNames(projectcss.all, sty.column__wefd)}>
                <Card
                  className={classNames("__wab_instance", sty.card__vlYLm)}
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qxcS
                      )}
                    >
                      {"Visi\u00f3n"}
                    </div>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vHv9
                    )}
                  >
                    {
                      "Nuestra visi\u00f3n es lograr concientizar a los propietarios de mascotas, sobre qu\u00e9 les estamos ofreciendo desde un plano nutricional. Si bien, no elaboramos alimento balanceado, sabemos que todos los detalles cuentan, y en este caso, los snacks no son la excepci\u00f3n. Cuidar la nutrici\u00f3n de nuestros compa\u00f1eros de cuatro patas debe ser una prioridad, y Nutreats tiene como meta lograr que m\u00e1s familias se sumen a la implementaci\u00f3n de dietas naturales en nuestros animales de compa\u00f1\u00eda."
                    }
                  </div>
                </Card>
              </div>
            </Stack__>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "puntosDeVenta",
    "h1",
    "contacto",
    "section",
    "mision"
  ],
  navbar: ["navbar"],
  puntosDeVenta: ["puntosDeVenta", "h1"],
  h1: ["h1"],
  contacto: ["contacto"],
  section: ["section", "mision"],
  mision: ["mision"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  puntosDeVenta: "div";
  h1: "h1";
  contacto: "section";
  section: "section";
  mision: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "h8C9fz9kVsxnVEjHjpK7So"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    puntosDeVenta: makeNodeComponent("puntosDeVenta"),
    h1: makeNodeComponent("h1"),
    contacto: makeNodeComponent("contacto"),
    section: makeNodeComponent("section"),
    mision: makeNodeComponent("mision"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Nutreats | Treats Deshidratados",
      description:
        "Treats Deshidratados para mascotas sin aditivos. Utilizamos materia prima de alta calidad.",
      ogImageSrc:
        "https://site-assets.plasmic.app/d8553e0d3a77045c0a3c25fd723ccdd8.png",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
